# Generated by Django 2.0 on 2018-03-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20180327_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_file',
            name='descript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
