# Generated by Django 2.0 on 2018-04-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('download', '0003_auto_20180327_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_file',
            name='download_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
    ]
