# Generated by Django 2.0 on 2018-04-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('download', '0004_download_file_download_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download_file',
            name='download_permission',
        ),
        migrations.AddField(
            model_name='download_file',
            name='download_permission',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
