# Generated by Django 2.0 on 2018-03-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
