# Generated by Django 2.0 on 2018-03-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homesite.Type'),
        ),
    ]
