# Generated by Django 2.0 on 2018-03-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0003_text_text_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='read_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='homesite.Text')),
            ],
        ),
    ]
