# Generated by Django 2.0 on 2018-03-18 17:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0004_read_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
