# Generated by Django 2.0 on 2018-03-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0006_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
