# Generated by Django 2.0 on 2018-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
        ('homesite', '0007_auto_20180319_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='file',
        ),
        migrations.AddField(
            model_name='text',
            name='file',
            field=models.ManyToManyField(to='download.Download_file'),
        ),
    ]
