# Generated by Django 2.0 on 2018-03-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
        ('homesite', '0008_auto_20180326_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='file',
        ),
        migrations.AddField(
            model_name='text',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='download.Download_file'),
        ),
    ]
