# Generated by Django 2.0 on 2018-03-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0010_auto_20180326_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.ManyToManyField(null=True, to='download.Download_file'),
        ),
    ]
