# Generated by Django 2.0 on 2018-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0011_auto_20180326_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.ManyToManyField(to='download.Download_file'),
        ),
    ]
